# Generated by Django 2.1.7 on 2019-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('etag', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
